# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/hello.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/hello.proto\")\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0c\x46ileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"S\n\x11UploadFileRequest\x12\x1d\n\x08metadata\x18\x01 \x01(\x0b\x32\t.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request2\x9c\x01\n\x07Greeter\x12,\n\x08SayHello\x12\r.HelloRequest\x1a\x0f.StringResponse\"\x00\x12\x35\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x0f.StringResponse\"\x00(\x01\x12,\n\x0c\x44ownloadFile\x12\t.MetaData\x1a\r.FileResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.hello_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=63
  _STRINGRESPONSE._serialized_start=65
  _STRINGRESPONSE._serialized_end=98
  _FILERESPONSE._serialized_start=100
  _FILERESPONSE._serialized_end=134
  _METADATA._serialized_start=136
  _METADATA._serialized_end=183
  _UPLOADFILEREQUEST._serialized_start=185
  _UPLOADFILEREQUEST._serialized_end=268
  _GREETER._serialized_start=271
  _GREETER._serialized_end=427
# @@protoc_insertion_point(module_scope)
